ni/niveristand-custom-device-build-tools

README.md

[x] This contribution adheres to [CONTRIBUTING.md](https://github.com/ni/niveristand-custom-device-build-tools/blob/master/CONTRIBUTING.md).
Links to the LabVIEW CLI that is now used by the build tools. Also makes note that Python must be installed on the build machine to use the build tools.
It contains the latest information about what is needed for a build machine setup to use the build tools.
Tested links go to correct locations.

Update README with link to new CLI

---

src/ni/vsbuild/Pipeline.groovy
src/ni/vsbuild/packages/AbstractPackage.groovy
src/ni/vsbuild/packages/Buildable.groovy
src/ni/vsbuild/packages/Nipkg.groovy
src/ni/vsbuild/packages/PackageFactory.groovy
src/ni/vsbuild/stages/Archive.groovy
src/ni/vsbuild/stages/Package.groovy
vars/buildSetup.groovy
vars/copyFiles.groovy
vars/getWindowsVar.groovy
vars/nipkgBuild.groovy
vars/versionReplacementExpressions.groovy

Enables building nipkg installers as part of the build pipeline.
We want to test the binaries that we would actually ship. This change enables us to test the actual installers that would be used in VeriStand systems.
[Builds](http://coordinator/job/VeriStand/job/buckd/job/testbuild/) of branches master, release-18.1 and dev/package-build. Only master and release build nipkg installers and dev branches do not. Repos using the build tools still need to be updated with control files and new build.toml information to use the enhancements in this change.

Build nipkg of binaries

---

src/ni/vsbuild/packages/AbstractPackage.groovy
src/ni/vsbuild/packages/Buildable.groovy
src/ni/vsbuild/packages/Nipkg.groovy
src/ni/vsbuild/packages/PackageFactory.groovy
src/ni/vsbuild/stages/Package.groovy

Enables nipkgs to specify different install locations based on LabVIEW/VeriStand version.
The SLSC custom devices install to different locations between VS 2016 and VS 2017. This allows a single build.toml file to specify which install location should be used.
Built the EDS custom device for 2018 and 2016. The package contents are staged to different locations as specified in the build.toml file.

Allow build.toml to specify a version-specific install location

---

resources/post_pictures_to_pull_request.py

Make images posted by the diff bot be collapsible, so they can be expanded individually without taking up too much screen space.
Having all of the images open by default is unwieldy.
Test diff: https://github.com/rtzoeller/niveristand-chassis-timesync-custom-device/pull/4

Make diff images collapsible

---

resources/merge_release_branch.py

Adds a utility script to keep release branches in sync with master. We should automate running this script in the future.
We want to track this script somewhere; the build tools repo makes sense.
Ran the script with the following file contents as input and confirmed it bumped the release branch to be in sync with master. Multiple repositories can be specified.
```
["NI Synchronization"]
url='https://github.com/ni/niveristand-chassis-timesync-custom-device.git'
directory='niveristand-chassis-timesync-custom-device'
version=19.0
```

Add utility for syncing release branches with master

---

vars/diffPipeline.groovy
vars/lvDiff.groovy

- The diff bot should install its own dependencies in a virtualenv, so that it does not require additional software to be installed on the build machine
- The diff bot timing out should not break the build
The dependencies changes get the diff bot working on the new build nodes, and the 
Build where the diff bot does not time out: http://coordinator/job/VeriStand/job/rtzoeller/job/niveristand-chassis-timesync-custom-device/view/change-requests/job/PR-5/25/console
Build where the diff bot times out: http://coordinator/job/VeriStand/job/rtzoeller/job/niveristand-chassis-timesync-custom-device/view/change-requests/job/PR-5/26/console

The diff bot should manage its own dependencies and fail silently on timeout

---

resources/labview_diff.py

Reduce the VIs being diffed to only the ones modified in the current pull request.
Previously we looked at all VIs which had been modified between the pull request and master. This unintentionally included any VIs which had been changed on master (i.e. another pull request had been submitted) but not on the pull request branch.
We are diffing VIs which the current pull request did not modify.
Running the git command by hand to see what files it lists as modified.

Ignore modifications present on the target branch when diffing

---

vars/buildDependencies.groovy

Fixes #35.
We currently fall back to master when trying to build dependencies if the branch name contains a "/". This affects dev and release builds for the SEECD.
Kicked off a build on a dev branch containing a slash, confirmed it chose the correct (non-master) branch. http://coordinator/job/VeriStand/job/ni/job/niveristand-scan-engine-ethercat-custom-device/job/dev%252Fadd_9266/7/console

Replace "/"s in branch names with the URL encoding

---

resources/LabVIEW.exe.config
resources/assemblyVersions.properties
vars/copyProjectConfig.groovy

Enables the build system to use a version of the VeriStand assemblies other than \<year\>.0.0.0.
Also simplifies redirection so we don't have to modify both the old version and new version in the `.config` file. Only the current version is now required.
VeriStand 2019 uses a different versioning scheme, so the current method of redirecting assemblies is insufficient for building new custom devices.
Built Synchronization custom device 2016-2019.
[Results](http://coordinator/job/VeriStand/job/buckd/job/niveristand-synchronization-custom-device/job/master/3/)

Override default VeriStand assembly versions

---

src/ni/vsbuild/stages/Archive.groovy
vars/getComponentParts.groovy

Decouples the job name component parts from the GitHub Branch Source Plugin.
- If only a repo and branch name exist, allow getComponentParts() to still return these values.
- Only archive to organization directory if the organization is defined.
Fixes #48 
- Built [testbuild component](http://coordinator/blue/organizations/jenkins/VeriStand%2Fbuckd%2Ftestbuild/detail/master/46/pipeline) using changes to verify the GitHub Branch Source Plugin job names still work correctly.
- Tested logic at https://groovy-playground.appspot.com/ to make sure the paths are correctly calculated using the new algorithm.

Enable multibranch pipeline without GitHub

---

src/ni/vsbuild/packages/Nipkg.groovy

Allows the user to specify an empty install path for nipkgs.
Virtual packages contain no payload, they just set recommends/suggests/other relationships between packages. NIPM store items are generally virtual packages and the custom device feed will use a virtual package as the top-level package.
[Built nipkg](http://coordinator/blue/organizations/jenkins/VeriStand%2Fbuckd%2Fniveristand-custom-device-virtual-package/detail/release%2F19.0/3/pipeline/5) with an empty path.

Enable building empty (virtual) packages

---

src/ni/vsbuild/packages/Nipkg.groovy
vars/copyFiles.groovy

Does not install the `manifest.json` file when the custom device is installed. While it would be nice to install the manifest with the custom device, currently, what you get is a single `installer` directory and only the manifest of the last custom device that was installed. This makes it useless and wasteful.
Fixes #40 
Built a [test release](http://coordinator/job/VeriStand/job/buckd/job/testbuild/job/release-18.1/134/) and the manifest is not included in the installer.

Remove manifest from nipkg installer

---

vars/buildDependencies.groovy

Tries to match branch names for dependency builds based on the branch initializing a pull request. If this is not a PR build, the env variable won't exist, so fall back to the original implementation.
Fixes #56 
Built a PR with dependencies. Branch selection shown below. The item was not found because there is already a PR for the corresponding branch, but the logic to choose the branch name is correct.

Use change branch for dependencies in PR builds

---

src/ni/vsbuild/BuildConfiguration.groovy
src/ni/vsbuild/Pipeline.groovy
src/ni/vsbuild/packages/Nipkg.groovy

Enables a user to put the _{veristand_version}_ or _{labview_version}_ tags anywhere in `build.toml` and have them evaluated without having to write extra code into each stage.
Fixes #68 
Test build: http://coordinator/job/VeriStand/job/buckd/job/testbuild/job/release%252F19.0/3/

Evaluate version tags during build initialization

---

vars/getComponentParts.groovy

PR #49 caused some weird flakiness where sometimes Jenkins doesn't correctly evaluate the organization. Simplify the code and do a simple check to see if organization exists.
Eliminates random build failures due to evaluation of component parts in the job name that occurred when looping through different items.
Ran a [test build](http://coordinator/job/VeriStand/job/buckd/job/testbuild/job/release%252F19.0/5/) to make sure everything still works.

Handle case where organization doesn't exist

---

README.md

Fix the incorrect LabVIEW version in the README.
We are not mass compiling the repository to 2016 right now, so 2015 is correct.
The existing information is incorrect.
None.

Update LabVIEW version in README to 2015

---

src/ni/vsbuild/Pipeline.groovy
src/ni/vsbuild/stages/Archive.groovy

Checks if the `manifest.json` file exists after archiving. If not, the file is archived.
Due to a bug in Application Builder, the Routing and Faulting custom device has to create builds at `Source/Built` instead of our typical `Built` location. The `manifest.json` goes to `Built`, which is not archived for the Routing and Faulting custom device, so we have to add an additional step to archive it.
Without this, the automated tests won't run.
Fixes [niveristand-routing-and-faulting-custom-devcice-#4](https://github.com/ni/niveristand-routing-and-faulting-custom-device/issues/4)
[Built](http://coordinator/job/VeriStand/job/ni/job/niveristand-routing-and-faulting-custom-device/job/dev%2Fmanifest-test/10/) and ensured `manifest.json` is correctly archived.

Archive manifest if not automatically included

---

src/ni/vsbuild/packages/AbstractPackage.groovy
src/ni/vsbuild/packages/Nipkg.groovy
src/ni/vsbuild/packages/Zip.groovy

Add support for building packages that install to multiple roots.
This is needed to support installing `.bin4` files for example finder integration as part of LabVIEW support packages.
- [Multi root build](http://coordinator/job/VeriStand/job/rtzoeller/job/testbuild/job/release%252F19.0/12/console)
- [Virtual package build](http://coordinator/job/VeriStand/job/rtzoeller/job/niveristand-custom-device-virtual-package/job/release%252F19.2/1/console)

Support building .nipkg packages that install files to multiple roots

---

resources/merge_release_branch.py

Sample output:
```
********************************************************************************
Merging release branch '19.2' for Routing and Faulting
********************************************************************************
On branch release/19.2
Your branch is up to date with 'origin/release/19.2'.
nothing to commit, working tree clean
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
Already up to date.
Switched to and reset branch 'release/19.2'
Your branch is up to date with 'origin/release/19.2'.
Everything up-to-date
Branch 'release/19.2' set up to track remote branch 'release/19.2' from 'origin'.
********************************************************************************
Merging release branch '19.2' for Message Library …
```

[merge_release_branch.py] Print repository name in a banner before merging each repo

---

src/ni/vsbuild/StringSubstitution.groovy

Add the legacy product upgrade codes for VeriStand and LabVIEW as substitution variables. Also add trivial substitutions for versions that have proper package names, for convenience when using with the legacy codes. The substitutions are now processed multiple times (until no more substitutions occur), which allows for nesting.
Due to LabVIEW 2017 having an SP1 release (with a separate legacy upgrade code), we can't get away with just defining the upgrade codes per version. Instead, we have to provide a substitution that can handle providing multiple packages, which means handling the version number of those packages as well. This is unfortunately ugly, but it should be easy to remove once LabVIEW and VeriStand 2017 are no longer supported.
For example, `Depends: …

Add legacy product upgrade codes as substitution variables

---

vars/copyProjectConfig.groovy

Creates a new object for the config file string to ensure the correct config file is copied when there are multiple projects to be built.
The Routing and Faulting custom device build is currently failing because `configFileName` is not being declared as a separate object, so multiple calls can result in `configFileName` not matching `projectPath`.
[Built the Routing and Faulting custom device](http://coordinator/blue/organizations/jenkins/VeriStand%2Fni%2Fniveristand-routing-and-faulting-custom-device/detail/master/112/pipeline) using the dev branch build tools and verified the correct files are being placed for each project.

Fix config files not being correctly copied

---

src/ni/vsbuild/Pipeline.groovy

Assigns a new set of stages for each parallel process in the pipeline instead of using class data. This avoids the race condition that causes #50.
Fixes #50 
[Built](http://coordinator/blue/organizations/jenkins/VeriStand%2Fni%2Fniveristand-custom-device-message-library/detail/master/536/pipeline) a library to make sure all of the staging still works as expected.
The above build does not prove that the issue is fixed, but does verify no regression in build behavior from this change.

Fix parallel pipelines building for incorrect version

---

src/ni/vsbuild/BuildConfiguration.groovy
src/ni/vsbuild/Pipeline.groovy
src/ni/vsbuild/stages/Archive.groovy
vars/setLabVIEWPath.groovy
vars/toml2json.groovy

Fail builds early if the archive step would overwrite existing data. This can happen if the Jenkins build numbers reset, or e.g. due to multiple repositories unintentionally exporting to the same location.
Also refactor the `build.toml` processing to only convert toml -> json once, and then re-use the json in memory. 
We have seen issues with Jenkins losing the build numbers and silently overwriting build outputs.
Built a custom device successfully, and then renamed that build output to the next build number. The subsequent build failed early as expected.

Do not clobber existing build outputs

---

resources/get_changed_files.py
resources/git_utilities.py
resources/labview_diff.py
src/ni/vsbuild/Pipeline.groovy
src/ni/vsbuild/packages/AbstractPackage.groovy
src/ni/vsbuild/packages/Nipkg.groovy
src/ni/vsbuild/stages/Package.groovy
vars/getChangedFiles.groovy

Allow package steps to specify files that impact their output. This is used as a heuristic for rebuilding packages during pull requests. Currently this includes the `build.toml` file, and `control` and `instructions` files for nipkg steps.
We currently either have to manually force packages to be built when testing, or blindly submit code and wait for a release branch to pick it up. This should give us more confidence when reviewing changes, without building packages for every change.
I've built a few pull requests that both do and do not trigger installer builds; I intend to test it on Routing and Faulting (which builds multiple packages) before submitting.

Build packages for pull requests that modify package-related files

---

vars/getChangedFiles.groovy

Checks for changed files against the target branch for a pull request.
The default is to check files against `origin/master`, but there may be some one-off case where a PR has a target branch that is not `master`. In these cases, the build will fail with
> fatal: ambiguous argument 'origin/master...': unknown revision or path not in the working tree.
Ran a replay on a failing build and the [build passed](http://coordinator/blue/organizations/jenkins/VeriStand%2Fni%2Fniveristand-embedded-data-logger-custom-device/detail/PR-19/10/).

Pass target branch for checking changed files

---

docs/Advanced Usage.md

Document using _DEP_DIR to override a dependency.
Using _DEP_DIR is needed for pull request builds when adding module support to https://github.com/ni/niveristand-scan-engine-ethercat-custom-device.
N/A

Document _DEP_DIR dependency overriding

---

docs/Advanced Usage.md

Add a line to the documentation for overriding dependencies to highlight the environment variable name.
It was pointed out that the `_DEP_DIR` environment variable name did not stand out in the code snippet. I couldn't get the text to be bolded in the code snippet, so this seemed the next best thing.
N/A

Bold `_DEP_DIR` environment variable in documentation

---

src/ni/vsbuild/Pipeline.groovy
src/ni/vsbuild/stages/Archive.groovy

Check for the existence of a `norebuild` file prior to starting a build which contains an archive step.
We want a way to prevent new exports from being created for branches which are final.
I ran a [build](http://coordinator/job/VeriStand/job/rtzoeller/job/niveristand-synchronization-custom-device/job/release%252F20.0/6/) on a release branch without the file and confirmed that it exported as expected. I created the `norebuild` file and confirmed the [build failed](http://coordinator/job/VeriStand/job/rtzoeller/job/niveristand-synchronization-custom-device/job/release%252F20.0/7).

Allow creating `norebuild` file to prevent rebuilding a branch

---

src/ni/vsbuild/Pipeline.groovy

addresses https://github.com/ni/niveristand-custom-device-build-tools/issues/96#issue-664485295
Increases the timeout from 5 to 10 minutes for the script responsible for checking out repos from version control.
To prevent future build failures of the DSF Custom Device Repo as this repo contains many files and consistently requires more than 4.5 minutes to check out from version control (#96)
Verified that 10 minute timeout is sufficient for [DSF Custom Device](https://github.com/ni/niveristand-data-sharing-framework-custom-device) through review of build logs.

change timeout from 5 to 10 minutes.

---

src/ni/vsbuild/steps/LvBuildStep.groovy

Using local dependencies supports substituting the target in the library path. This change enables the same substitution for external dependencies instead of assuming the target is always immediately after the version.
The Data Sharing Framework plugins depend on the DSF custom device, which exports libraries to subdirectories. This change enables the build tools to correctly build the path to the libraries to be copied.
Ran a [replay build](https://nijenkins.amer.corp.natinst.com/blue/organizations/jenkins/NI%2Fniveristand-data-sharing-framework-custom-device-plugins/detail/PR-2/5/pipeline) with these changes to verify the files are correctly copied (the build failed, but the copy was good).

Support target substitution in external deps

---

resources/find_latest_directory.py
resources/get_changed_files.py
resources/git_utilities.py
resources/github_commenter.py
resources/labview_diff.py
resources/merge_release_branch.py
resources/needs_rebuild.py
resources/post_pictures_to_pull_request.py
resources/toml2json.py

Reformat our python code to comply with https://github.com/ni/python-styleguide.
This was done automatically using `black` with a configured line length of 100.
This is a nonfunctional change that updates our code to use a standardized convention.
None - `black` is a well tested tool which should not impact functionality.

Reformat python code to comply with ni-python-styleguide

---

src/ni/vsbuild/packages/Nipkg.groovy

Log intermediate steps for building nipkgs, including the control file name.
@Karl-G1 and I were confused by the lack of logs in this area - it wasn't clear if a package was not being built, or if was just not being archived correctly.
Adding the control file name to the output should make it easier to grep for things.

Log active control file name in nipkg build step

---

src/ni/vsbuild/Pipeline.groovy

Create a `.finished` file when the build succeeds, so other processes can check this status.
We want the feed build tool to only pull from finished builds.
Ran a build with these changes and confirmed the file was added after all LV versions were built.

Create a .finished file when the build succeeds

---

resources/git_utilities.py

Remove unnecessary `HEAD` argument.
Builds are failing because git is returning the help text, rather than expected output.
git previously accepted input of the form `git diff origin/main... HEAD`, but now fails on the space. The expected input is `git diff origin/main...HEAD`, but we can omit `HEAD` entirely.
Re-ran the failed build and made it past the point of failure.

Fix build error with git 2.29

---

vars/diffPipeline.groovy

Ignore error following VI diff if directory cleanup fails. Subsequent builds will clean the directory before doing anything, so this failure is inconsequential.
Our build nodes had some software upgrades over which we have no control. These upgrades have caused failures deleting files following diffs because the file system still has these files locked. This failure should not fail an entire build.
Ran a replay of a failing build. Verified I see the failure string printed but the build still passes.

Don't fail build on directory cleanup failure

---

src/ni/vsbuild/stages/Archive.groovy

Fixes an issue where build outputs to locations other than `Built` cause installers to not be archived. This was introduced in #115 
No installers are archived correctly even though they are built.
Ran a replay of a build where installers were not copied and now they are.

Fix installer archiving issue

---

src/ni/vsbuild/stages/Archive.groovy

fix typo
should fix this build error:
>org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
file:/F:/Jenkins/jobs/NI/jobs/niverista.97m919c3ad81.om-device/branches/PR-54/builds/4/libs/vs-build-tools/src/ni/vsbuild/stages/Archive.groovy: 8: expecting ''', found '\r' @ line 8, column 58.
ing INSTALLER_DIR = 'installer
^
None yet. Hoping this will unblock PR builds

fix typo by adding back in a closing '

---

docs/Toml Help.md
src/ni/vsbuild/Architecture.groovy
src/ni/vsbuild/LabviewBuildVersion.groovy
src/ni/vsbuild/steps/LvBuildStep.groovy
src/ni/vsbuild/steps/LvStep.groovy

Allows a `build.toml` file to designate a specific bitness for running a given build step. If no bitness is provided, the step will run for any build. If **bitness** is provided, either 32 or 64, the build step will only be run in cases where a LabVIEW of that bitness is used.
The Scan Engine and EtherCAT custom device will need to build only certain build specs for 32-bit LabVIEW due to dependencies not being available in 64-bit LabVIEW.
Ran builds with no bitness specified, 32 specified, and 64 specified, and verified build specs were only run for the correct bitness.

Enable building steps based on bitness

---

src/ni/vsbuild/BuildConfiguration.groovy
src/ni/vsbuild/Pipeline.groovy
src/ni/vsbuild/StringSubstitution.groovy
src/ni/vsbuild/packages/Nipkg.groovy
src/ni/vsbuild/steps/LvBuildStep.groovy

Define the following variables:
| Variable | 32-bit value | 64-bit value |
|---|---|---|
| `pkg_x86_bitness_suffix` | `-x86` | |
| `nipaths_64_bitness_suffix` | | `64` |
These variables will allow packages to install to the correct bitness NI-Paths and depend on the correct bitness packages.
Built https://github.com/ni/niveristand-routing-and-faulting-custom-device/pull/266 and confirmed that the R+F LabVIEW package could be installed, and that the VIs and palettes appeared correctly in LabVIEW 64-bit.

Add variables to help with builds of differing bitness

---

src/ni/vsbuild/Pipeline.groovy
src/ni/vsbuild/packages/DefaultPackageStrategy.groovy
src/ni/vsbuild/packages/Nipkg.groovy
src/ni/vsbuild/packages/PackageFactory.groovy
src/ni/vsbuild/packages/PackageStrategy.groovy
src/ni/vsbuild/packages/PostArchivePackageStrategy.groovy
src/ni/vsbuild/stages/Package.groovy
vars/copyFiles.groovy

Parses `build.toml` to determine if some packages should be built after both the 32- and 64-bit builds of a specific LabVIEW version have completed. If both bitnesses are required in the package, that package is built after each version build has completed and archived its artifacts.
**Note**: There will also need to be updates to the `Toml Help.md` file, but I will file an issue and address that once we have Scan Engine building.
The Scan Engine and EtherCAT custom device needs this capability to build packages for VeriStand 2021. Because VeriStand 2021 will build against LabVIEW RT 64-bit, we need the custom devices to build in 64-bit LabVIEW. But, some drivers are lacking 64-bit support, so we build the configuration and engine in 64-bit, but build things requiring other driver support …

Enable building packages for multiple bitnesses

---

vars/diffPipeline.groovy

Enables a calling Jenkinsfile to configure the timeout for running the LabVIEW diff.
Some diffs take longer than the default 60 minutes to complete. This change allows the user to configure a timeout such that the diff will finish.
Note: I didn't just increase the default value because, in many cases, a diff that takes longer than an hour begins to become too complex to be useful as just a visual diff in github. In those cases, I don't want to wait longer than the default time before the diff step ends.
Ran a replay of a PR build with the new file and a timeout of 120 minutes set. The build log file indicates the timeout will be "2 hr 0 min".

Make diff timeout configurable

---

docs/Toml Help.md
src/ni/vsbuild/steps/LvBuildStep.groovy
src/ni/vsbuild/steps/LvStep.groovy

Adds `minimum_version` property to `build.toml` to prevent building if a project uses unsupported features from an older version of LabVIEW.
The [RDMA feature](https://github.com/ni/niveristand-data-sharing-framework-custom-device-plugins/pull/22) for Data Sharing Framework uses the NI-RDMA driver, which only supports LabVIEW 2020 and newer. The rest of DSF and its plugins support LabVIEW 2019. We don't want to drop 2019, but still need to build the RDMA plugin.
Ran a [test build](http://nijenkins.amer.corp.natinst.com:8090/view/Veristand/view/GitHub/job/NI/job/niveristand-custom-device-message-library/job/dev%252Fmin_version_test/5/) of the messaging custom device and verified 2019 was skipped with minimum version set to '2020'.

Skip building if version is too old

---

src/ni/vsbuild/packages/AbstractPackage.groovy

Returns only the number for the major version instead of appending `.0.0`.
It's possible we would want something beyond the `.0.0` version at some point, so just let the control file determine what is to be used after the major version.
N/A

Just return number for major version

---

src/ni/vsbuild/Pipeline.groovy

Selects the x64 architecture for running post-archive stages in the build pipeline. Post-archive should only be used for building packages containing both 32- and 64-bit binaries. In this case, always choose the 64-bit architecture for determining install paths.
Addresses AB#2092858 where the Scan Engine custom device is not correctly installing the scripting API, examples, or error files for VeriStand LabVIEW 2021.
Ran a replay build of a Scan Engine custom device PR build and verified the `nipkg` files will actually install and files are placed in the correct locations.

Choose x64 architecture for multi-bitness packages

---

src/ni/vsbuild/Pipeline.groovy
vars/cleanWorkspace.groovy
vars/diffPipeline.groovy

Attempts to retry calling `deleteDir()` when the first call fails.
The build machines have been more frequently hitting an issue where files are not released by LabVIEW in time to successfully call `deleteDir()` to clear the workspace. This change adds a retry with a 5 second sleep between attempts to give the OS more time to release the files.
Fixes #128 
Ran PR build and verified files are correctly deleted.
Jenkins [retry](https://www.jenkins.io/doc/pipeline/steps/workflow-basic-steps/#retry-retry-the-body-up-to-n-times)

Retry workspace deletion

---

src/ni/vsbuild/packages/AbstractPackage.groovy
src/ni/vsbuild/packages/Nipkg.groovy

Introduce new variable substitutions for control files, to enable packages to use the new quarterly release versioning scheme.
The custom device feed already uses this display version; this is the logical next step.
Replayed builds for with a control file using the new variables.

Add new variable substitutions for quarterly release versions

---

resources/labview_diff.py
vars/diffPipeline.groovy

Uses 64-bit LabVIEW to diff VIs instead of 32-bit.
We now have a custom device that is only supported in VS 2021 and later, which means we are only building with 64-bit LV. We need diffs for that repo. This change should be safe because all custom devices should now be building against at least one version of 64-bit LV.
Ran a build using only a 64-bit LV and verified diffs were created and posted to GitHub.
https://github.com/ni/niveristand-adas-toolkit-custom-device/pull/4

Use 64-bit LabVIEW for running diff

---

src/ni/vsbuild/StringSubstitution.groovy

Add support for LabVIEW-version agnostic dependencies.
Also remove support for VeriStand 2017 and 2018.
This is needed to support drivers like NI-SWITCH who now provide their LabVIEW support in a version independent way.
Replayed a Routing and Faulting build with the changes and inspected the generated packages.

Add support for LabVIEW-version agnostic dependencies

---

azure-templates/stages.yml
azure-templates/steps-build.yml
azure-templates/steps-pre-build.yml

1. fix "build Build" nomenclature on GitHub build status by adjusting stage/job naming
2. Add conditional logic to use System.PullRequest.SourceBranch instead of Build.SourceBranchName when building for a PR, because PR builds use a different source branch labeled "merge"
3. Changed if statements to be Elseif when relevant
4. Added Write-Error and Write-Output items to catch issues where invalid parameters are provided in the pipeline with explicit error information
5. Rearranged BuildSpec conditional logic to check for specific build operations instead of requiring a specific value in buildStep.target or buildStep.buildSpec for "build all" scenarios
This cleans up a few issues that were identified after first PR+push of the various build pipelines, and it clarifies the behavior in some …

Fix PR branch name, and add error checking and writing to catch user mistakes

---

azure-pipelines.yml
azure-templates/stages.yml
azure-templates/steps-build.yml
azure-templates/steps-post-build.yml
azure-templates/steps-pre-build.yml

1. changes codegen to work with all build specs (the limitation was based on an old design that was thrown out for the current design).
2. Also removes "pack" parameter, which is not needed now that there is a method for just cycling through "each" of a parameter.
3. Finally, adds an explicit definition of release versions and dependency skipping for troubleshooting
Needed for Scan Engine pipeline development.
See build pipeline results below.

change codegen to work for all build operations, and remove unnecessary pack parameter

---

azure-pipelines.yml
azure-templates/stages.yml

Update pipeline to use DevCentral instead of Users project.
This is necessary to move the builds to DevCentral.
Will run the pipeline as part of this PR.

Move pipeline to use DevCentral

---

azure-pipelines.yml
azure-templates/stages.yml
azure-templates/steps-pre-build.yml
src/ni/vsbuild/packages/AbstractPackage.groovy

Follow up to #134 which supports additional versions.
We want packages built this cycle to be versioned "2023 Q2".
PR build.
(Azure Pipeline) Checked the nipkg output:

Handle more quarterly versions than just 2023 Q1

---

azure-pipelines.yml
azure-templates/stages.yml
azure-templates/steps-pre-build.yml

source branch export path will now include any /* as directories (including dev and release, as well as others if used)
Release branch naming convention is release/XX.X, which currently cuts release from the path.
PR build outputs now save with the dev path in this branch for both PR builds (see output of this PR) and generic branch builds (see screenshot):

Fix branch name

---

azure-templates/stages.yml
azure-templates/steps-post-build.yml
test-build/control-a
test-build/control-b

* Adds a buildCounter variable that will iterate for each branch for each build.
* Sets buildCounter for PR builds to 9999
* Adds the branch name to nipkg outputs from nonrelease branches
* Add a variable to the control files to not duplicate packages since packaging is done for both bitnesses
* Add comment pointing an editor to scan engine custom device custom packaging
This is useful to help differentiate between different packages from the release branches, and it is used by some of the logic for release.
Ran three instances covered by the changes: 
1. PR build (use 9999 instead of buildCounter), 
2. manual build (works like CI), use buildCounter and append dev branch name
3. new branch with "release" in the name, use buildCounter, but don't append branch name

Add a Build Counter to iterate at the end of each nipkg_version of nipkg output

---

azure-templates/steps-post-build.yml

Add manifest file with git branch, commit, and URL for release builds
The manifest file is still used by the feed creation and ATS events to specify which branch, commit, and URL to clone to run tests against. This replaces the groovy logic that created the file for Jenkins builds.
Ran the build pipeline against this dev branch and an identical release/23.3 branch to test both cases:
[dev branch build](https://dev.azure.com/ni/DevCentral/_build/results?buildId=4456834&view=logs&j=d776b11b-d2bf-5943-1b8d-603570db92c3&t=8e9e3714-0ae4-56f4-d6c9-e7a9c6354283)
[release branch build](https://dev.azure.com/ni/DevCentral/_build/results?buildId=4456831&view=logs&j=d776b11b-d2bf-5943-1b8d-603570db92c3&t=8e9e3714-0ae4-56f4-d6c9-e7a9c6354283)

Add manifest file for release branch builds

---

azure-templates/steps-post-build.yml

There is a missing item that needs to be replaced in the nipkg control files:  {pkg_x86_bitness_suffix}.  Currently if you try to install scripting/example nipkgs, they will be confused that this variable is not replaced.
Fix packages to include the correct version prerequisites by replacing this suffix.

Add x86 suffix for packaging

---

azure-templates/steps-post-build.yml

Add ".git" to end of Git URL in manifest file
ATS is failing with message "Could not parse URL 'https://github.com/ni/niveristand-scan-engine-ethercat-custom-device'" after consuming the latest Scan Engine build with the manifest file creation. Comparing the new manifest to the old, we are leaving out a ".git" at the end of the URL.
- Created a new release/23.3 branch of this repo to validate manifest.json output
- Hand-edited the manifest.json files for release branch builds of Scan Engine CD and Sync CD, then validated the resulting feed can clone the repos and run tests.

Add ".git" to end of Git URL in manifest file

---

azure-templates/stages.yml

Changes the timeout in minutes to 120 to accomodate long build times for the PPLs in Comm Bus projects with LV 2020.
Currently some of the custom devices are timing out occasionally.
PR for this repo should continue to build successfully.

change timeout to 120 minutes

---

azure-templates/stages.yml

Allows build steps to not be specified, to allow a custom device (custom-device-wizard) to build with no build steps
Right now custom-device-wizard can't be built because buildSteps is required
Normal builds continue to work (can't test custom-device-wizard until this is submitted into main because azure pipelines won't let you choose a custom resource unless the base yaml can be compiled).

Add option for no build steps

---

azure-pipelines.yml
azure-templates/steps-build.yml
azure-templates/steps-pre-build.yml

* creates a new variable called workspaceDirectory that works like $PWD or %cd% to ensure paths are absolute and avoid any relative path errors
* Adds an optional parameter under a buildStep called projectOverride that will use the projectLocation as an absolute path if the projectOverride value is set to "Absolute", instead of a relative path inside of the repo.
an absolute path is needed for some internal tools used in building ADAS Toolkit custom device.
One of the build steps in azure-pipelines.yml now uses an absolute project path to test this behavior.  The PR build should only pass if it's working as desired.

Add optional parameter to define a custom project location

---

azure-templates/steps-build.yml

Errors if the dependency requested has no successful builds.
If a dependency is missing due to a mistake in the yml or a lack of build artifacts, it is better to throw the error in the dependencies step to make it clear that this is the issue, rather than more convoluted errors in the build steps themselves that may or may not communicate information about the missing dependency.
Ran this pipeline with missing dependency files:

Fail on missed dependency

---

azure-templates/stages.yml

removes an unused paramter with a default.
This was originally left in to keep builds from failing while it is being removed, now all builds have had this removed.
Looked through the custom devices to make sure quarterlyReleaseVersion has been removed.

Quarterly Release removed

---

azure-templates/powershell-scripts/build-step-setup.ps1
azure-templates/powershell-scripts/dependency-setup.ps1
azure-templates/steps-build.yml
azure-templates/steps-post-build.yml

Moves the powershell scripts for dependencies and build preparation to powershell scripts.  Command line does not have the same capabilities as powershell, so calling a batch script for CmdLine tasks is not feasible, but since they are relatively short with 1-2 calls inside, that shouldn't be too bad.
Continuing to improve readability and reusability of pipeline code.
This build should pass.

Move build steps inline powershell scripts to files

---

azure-pipelines.yml
azure-templates/powershell-scripts/dependency-setup.ps1
azure-templates/stages.yml
azure-templates/steps-build.yml

Adds a parameter to silently skip when dependencies fail.
SEECD includes dependencies in some bitnesses but not others, and this is the easiest way to accommodate it's unique needs.
SEECD pipeline can't be run before submission since it requires a top level parameter that doesn't existin build-tools main.
Committed the property temporarily to the pipeline and behaved as expected:

Optional error silence for SEECD

---

azure-pipelines.yml
azure-templates/powershell-scripts/packaging/copy-payload.ps1

Now that we are using payloads from nirvana archives, we do not need to include the build output path.
If this is not included, we will not have any payloads in the builds
PR Build output

shorten payloads

---

azure-pipelines.yml
azure-templates/powershell-scripts/check-count-size.ps1
azure-templates/powershell-scripts/define-essentials.ps1
azure-templates/powershell-scripts/packaging/copy-payload.ps1
azure-templates/stages.yml

* Adds a step to the Final Verification pipeline that compares the sizes and file counts in all of the package files output by the build to the last successful build of main
* This is the most common way that we manually validate a pipeline is building correctly.
* Tested with build-tools (see PR output), and also ran it with SLSC-12201 CD:

Add file count and size check in pipeline

---

azure-templates/powershell-scripts/check-count-size.ps1

Adds an _ to the match to ensure that packages will not include partial matches, to address FPGA Addon for example.
Some builds require this since they have packages that fully include the name of other packages, such as FPGA Addon.
Works with FPGA Addon:
Note:  the last successful build of FPGA Addon had empty packages:

add an underscore to ensure exact package name matches

---

azure-templates/powershell-scripts/check-count-size.ps1

Checks for whether a matching package actually exists in main before doing the comparison for file count and size.
If a package is added (e.g. support for a new verison of LabVIEW) this comparison should be skipped silently instead of erroring.
Temporarily removed the 2023 export for the latest in main for this PR build:
When running in this state, build still passes with packages skipped:

skip comparison of packages if there is nothing matching in main

---

azure-templates/powershell-scripts/check-count-size.ps1
azure-templates/powershell-scripts/packaging/manifest-release-tags.ps1
azure-templates/stages.yml

* Fails verification if package files have no files in them, now that we are checking anyway.
* If someone wants to build an empty package (just a control file for install recommendations) they can use the optional parameter **enableVirtualPackages: true** in the top level pipeline.
* Also updates a regex to use the literal period instead of a wildcard to avoid unexpected failures with certain branch names
Packages should not usually be empty, so we might as well catch the error case.
Also fixes a bug that would impact any dev branch with "nipkg" in the name
Tested with dev tools, which was making empty packages at the time of the test:
Then tested with a special branch of build-tools with enableVirtualPackage:
this works.
This PR should not fail, to verify the existing case.

Add empty package fail case, and fix nipkg branch issue

---

azure-templates/powershell-scripts/packaging/copy-payload.ps1

Not sure what this was originally for (I imagine it was to facilitate some duplicate files in the build-tools tests), but instead of skipping files, just force overwrites them.
Currently some of scan engine's files are being skipped.
Ran this with SEECD and the files that were missing are now included:

Remove existing files check

---

azure-templates/powershell-scripts/packaging/manifest-release-tags.ps1
azure-templates/steps-packaging.yml

Check whether `CD_INSTALLERPATH` is null before testing if the path is populated for release builds
Fix #186 
- [Ran a pipeline](https://ni.visualstudio.com/DevCentral/_build/results?buildId=4949729&view=logs&j=3bd4616a-ba05-5ecb-8884-5259017d0dbc&t=775180f8-36b4-5115-ef4b-6792bea0af0b) of Scan Engine Modules release/23.5 using commit f60ee9eaf28e2b1372424724d76385d3a081fbbd
- Pending PR build of this repo

Fix release branch builds with no packages

---

azure-templates/powershell-scripts/dependency-setup.ps1

When a branch builds, it will search for dependencies in dev branches of the same name first before defaulting to main.  This leaves the possibility with simultaneous build kickoffs that no existing .finished branch exists.  We should throw a meaningful error in this case.
Throws an error that hopefully doesn't require digging into the code to troubleshoot.
This is what shows currently:

Add error when a dev branch dep is missing

---

README.md

Update readme about archiving Jenkins support
I created a `jenkins` branch to archive builds support for Jenkins based on the 54320887d68d369781e1539563d6fbd0d8a68714 commit before Azure pipeline updates were made (plus cherry-picking the relevant change from 72f20e7771eacb1081bee239aeef540563c1434c). This branch needs updated with this disclaimer, as well as getting added write protection to avoid PR-less pushes.
None

Update readme about archiving Jenkins support

---

README.md

Update readme to remove Jenkins and add Azure Pipelines
Jenkins support has been archived in the `jenkins` branch. We do not need this info in the readme in main.
I also paired down the user guide info from the readme and instead link to the docs getting added in #169
None

Update readme to remove Jenkins and add Azure Pipelines

---

azure-templates/powershell-scripts/packaging/stage-directories.ps1
test-build/control-a

adds "major version" to support the DSF control file: 
https://github.com/ni/niveristand-data-sharing-framework-custom-device-plugins/blob/5feaad540ca53969f3dbd1c79c811c0a3a14c0ea/control_dsf_plugins#L15C163-L15C163
We need this working by the next release of DSF at the end of the cycle
Built DSF off of this branch of build-tools:

add a major version to support DSF control file

---

azure-templates/powershell-scripts/define-build-variables.ps1

Include the patch version in the display string, e.g. 23.8.1 renders as `2023 Q4 Patch 1`.
Provide a way to distinguish patch builds from the initial one.
Built 23.8.1 branch of a custom device and inspected the package file.

Include patch version in the quarterly display string

---

resources/labview_diff.py

Update regex to include controls  in VI diffs
Custom Devices store lots of useful information in controls. This change adds diffs of controls to the comments posted on PRs.
Locally tested to see diffs of .ctl files

Update regex to include controls in VI diffs

---

azure-templates/stages.yml

TODO: Check the above box with an 'x' indicating you've read and followed [CONTRIBUTING.md](https://github.com/ni/niveristand-custom-device-build-tools/blob/main/CONTRIBUTING.md).
This change ensure that the packaging job uses an agent from the desired pool and with the desired capability similar to others steps in the stages.yml file.
The lack of a pool and demands section in the packaging job open up the step to running on a undesired agent when specifying a pool other than DevCentral-VeriStand-CustomDevices. Specifically, the ADG System R&D team uses their own pool of agents and were encountering an issue where the packaging job would choose an agent other than the ones they'd like to use that are in the same pool but not owned by our team. This fixes the issue while retaining the …

Add pool and demands to packaging step to ensure specific agents

---

azure-pipelines.yml
azure-templates/powershell-scripts/define-build-variables.ps1
azure-templates/stages.yml
docs/Azure Pipeline YAML.md
test-build/dependency-builder/Readme.md

TODO: Check the above box with an 'x' indicating you've read and followed [CONTRIBUTING.md](https://github.com/ni/niveristand-custom-device-build-tools/blob/main/CONTRIBUTING.md).
Remove 2021 and Adds initial support for LabVIEW and VeriStand 2025.
needed for building other github [CDs] repo.
Needed for a future release.
PR build

Drop 2021, Add 2025
